"""add projects table

Revision ID: cdb9f848e0f3
Revises: ce3a9bbc6e9e
Create Date: 2025-07-18 23:38:08.558955

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import text


# revision identifiers, used by Alembic.
revision: str = "cdb9f848e0f3"
down_revision: Union[str, None] = "ce3a9bbc6e9e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Delete existing tasks with no owner
    conn = op.get_bind()
    conn.execute(
        text(
            """
        DELETE FROM tasks
        WHERE owner_id IS NULL;
    """
        )
    )

    op.create_table(
        "projects",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("owner_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("tasks", sa.Column("project_id", sa.UUID(), nullable=True))
    op.alter_column("tasks", "owner_id", existing_type=sa.UUID(), nullable=False)
    op.drop_constraint(op.f("tasks_owner_id_fkey"), "tasks", type_="foreignkey")
    op.create_foreign_key(
        "tasks_owner_id_fkey",
        "tasks",
        "projects",
        ["project_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "tasks_project_id_fkey",
        "tasks",
        "users",
        ["owner_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("tasks_owner_id_fkey", "tasks", type_="foreignkey")
    op.drop_constraint("tasks_project_id_fkey", "tasks", type_="foreignkey")
    op.create_foreign_key(
        op.f("tasks_owner_id_fkey"),
        "tasks",
        "users",
        ["owner_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.alter_column("tasks", "owner_id", existing_type=sa.UUID(), nullable=True)
    op.drop_column("tasks", "project_id")
    op.drop_table("projects")
    # ### end Alembic commands ###
