
services:
  db:
    image: postgres:16
    container_name: tasktracker-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tasks
    ports:
      - "5432:5432"            # host→container
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:                       # named volume lives outside the container
