
services:
  db:
    image: postgres:16
    container_name: tasktracker-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: tasks
    ports:
      - "5432:5432"            # host→container
    volumes:
      - pgdata:/var/lib/postgresql/data
       
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  pgdata:                       # named volume lives outside the container
